/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://lsmrj3z3mjfylf5atzhtenqmdq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4fb5ibbzwfcopeit74waa3as7e",
    "aws_cognito_identity_pool_id": "us-east-1:8eaecff8-f510-4317-ab6e-bf59f84052d4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aGozQGOIJ",
    "aws_user_pools_web_client_id": "292fa2i73untad3mq50ha2vv20",
    "oauth": {
        "domain": "raintreeapie713631e-e713631e-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://sprint2-demo-bugfixes.d30osreoi07r0e.amplifyapp.com/",
        "redirectSignOut": "https://sprint2-demo-bugfixes.d30osreoi07r0e.amplifyapp.com/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "10",
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "raintreeresources134916-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "raintreeapitoken-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
